---
# patroni_postgresql_cluster/handlers/main.yml

- name: 'Trigger systemctl daemon-reload'
  ansible.builtin.systemd:
    daemon_reload: 'yes'

- name: 'Restart patroni'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    state: 'restarted'
